language: go
go:
- 1.7.x

services:
   - docker

before_install:
   - docker build -t hello_world .
   - docker ps -a

#- docker run -d -p 9090:9090 hello_world


### For codecov
script:
  - docker run hello_world  -v 
  - docker run hello_world "bash <(curl -s https://codecov.io/bash)>"
