language: go
go:
- 1.7.x
services:
- docker
before_install:
- docker build -t liam-lai/ptt-alertor .
- docker ps -a
script:
- docker run -d -p 9090:9090 liam-lai/ptt-alertor
before_deploy:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- export AWS_ACCESS_KEY_ID=AKIAIE4PWSIS5SCEF3TA
- export AWS_Docker_Repo=896146012256.dkr.ecr.us-west-2.amazonaws.com/ptt-alertor-repo
- eval $(aws ecr get-login --region us-west-2)
- docker tag liam-lai/ptt-alertor:latest $AWS_Docker_Repo:latest
- docker push $AWS_Docker_Repo:latest

deploy:
- provider: script
  script: 
  - bash ./deploy/ecs-deploy -r us-west-2 -c ptt-alertor-cluster -n ptt-alertor-service -i $AWS_Docker_Repo -m 0 -M 200 -t 240 -D 1
  on:
    branch: master
notifications:
  slack: meifamily:9oYnHKf0nlRn8QafX4PRZ1lC
env:
  global:
  - secure: pcK6KNugqPILq29+pgPfbPNue+iK8w+4OtiZZwHBhsJ9bsggqBHfDRhGJd7PH/AecNkz4rYuBUea80BQcB/seRKtiHiBYrGPq+Bh+6KFTSoocBeRRB1gxVMonaAUd36FNdbvozIimA1GCCjWzaUe/BfwESmmuBIzEqf1wys9qV7F3YRASDeeG377CTDgAgBw7ClFofqyh4KXK8CmbIgOGW/+fsatxdA8dGB9ATWPzKICY8qJIjU/BXFuQuRQhv48d5ePRzVUNcx1qxTKbc9XHT3gmpxoBcNB6nPDUY9/MFfq0hz7RGAUl2RQRKtVvN3Hi3iVwwSoQXV8NDJS8Rbns2XX3KbjfT5UN91J7tBh13sYM6z25UTX3/R/d+wrJS4B63Lfs0UxpzIzLMlj/jnzEN1l6At4p2SPpNscGikORbEQ+AO9bjN3CTN9Zdy4PVA10rjOv+ejd+6Ta/Khi4MjsWGx388xvcfM7Cf8CGHJz1EiNpbWsGnea/p1mdmGHzzRSSNKV410PjWwgj5o0qk3lQFppbnDJmcXGhiQobvZ7oDryt9fabzz68jZ1BWzPnRyjmlcJQc3boyyMzuXT/v+u8QbqJkKXM5CjfqP+9mL0UGT+KULBZC7V2oDAnj9LDGyYSVDyT+KgEDkyU16AMUTvF2gtzlH2jkcMk/eNdhzFi0=
