language: go
go:
  - 1.15.x
cache:
  directories:
    - "$HOME/.local"
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - chmod +x ./test.sh
  - pip install --user --upgrade awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - go get
before_script:
script:
  - "./test.sh"
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  - docker build -t meifamily/ptt-alertor .
  - eval $(aws ecr get-login --region us-west-2 --no-include-email)
  - docker tag meifamily/ptt-alertor:latest $AWS_Docker_Repo:latest
  - docker push $AWS_Docker_Repo:latest
deploy:
  - provider: script
    script:
      - bash ./ecs-deploy -r us-west-2 -c Production-Cluster -n Ptt-Alertor -i $AWS_Docker_Repo -m 0 -M 100 -t 600 -D 1
    on:
      branch: master
notifications:
  slack: meifamily:9oYnHKf0nlRn8QafX4PRZ1lC
env:
  global:
    - GO111MODULE=on
    - AWS_ACCESS_KEY_ID=AKIAVDUITF6YSMX5ZSVN
    - AWS_Docker_Repo=351400046513.dkr.ecr.us-west-2.amazonaws.com/ptt-alertor-repo
    - secure: Ft0NQQUxY2Y7uHbH8Lhk736p6RCSkkXdm5j6pOX4/y9DL5WYnWEpBgi1H+4Z8WvmpDkYKiuXkFkqB+tjFGbL5pCa5jEEilMVRN638KQ8G43E4G6PVzLFpAe/di2gU3uVa2jnR3G8pOv/uSgbFTo6HXQc9Hf4/DH591sMDQNha7YAKMMIFDAw92zMZhOp+P/ulaL0PCZP3CvRdc+0cKBRZtZq8H9Gi5ZE7TfJqnh/7w40NWDoqaNE3lf0/DRpORiuWM1lQ91+LOSIPZm5MQeMhZig0NylGPEdhnOkhpS++pNWKI9LHhKXqCKVhJeAkQjt6Srl9SLIqPGNaRDhbUyKOZk948U/H4KOVa0CtVe/WL18WI6QLSjMs3EwtHDSJkBvUz9nvC1uGBvia716q9htekToRLJxPq8RsbIu6+S9WRXXXa9U2oaQQsueo3WPLwdrBsm+YKrP7yjeYzNeZZqsqhDpBZ7uyo9PLkOtIxdfiRSeSOuNdCLT+oIU6t0aCZWgm1Q/SIin6eTRreys4VGLdaWW4JhG6vUTd8bSP00LEbk8wlQ0C1/CIpwjDS2OUiXfmzyBXS5KujEz/MwmrwlLJYNVgWbUlR/czBPui8zfxqru5OGDpzY/QVpL/LE1dbxTUo18bq819VYPkqNJyETKjOjrSzKGlY56WSpLSJjyZ6U=
    - DOCKERHUB_USERNAME=dinos80152
    - secure: RW/kxgWji9LEbc+oRbIKQbscoNWBnjRAHimVYekBv+li8w/LNqrjIqsZJblbT53Iizh5SJRXNs1DpRlDOgF+XbSCXzrNhWCwGLCkfLiG06qJ0VsymtzJf5kIgX1n8pOB6cMs0p8bbhMOf2r0yw27EZNVUpTJbrYilT8MrnbCke1gYEnWBMhvTPJYy6KeWjwPxDEVAOsoguPvUzWFHsRpt4qbMoA3L/x6Em6pFRnOesCEZeGuzWIg/qvCd/guUsflSWwdtruOa95egQ/DhwU521Z+aIknL+u9Bps5Uf6gXzIDVt1DFoEMl/CulOMygAGZGzAxdkFNjPMc1qLPKewfmR9IrKJviNLj+8qZkTp/3PPQ/ZBuVdcayOGL5Epi/8YIRIFfxCHO+n0PcvQo72ZV1Nl1Ie0ZF01WDDNMWSg4uXCmUuLPhB6NBZHZpYKDFUpWDyeRAqPwTGxFzB8yYx6rk2AdNo085+bn9W3/b9qAVs56VHr9srqqpREQr/JqLOucJ4+b950NEufKodHLhFUiBKnnwRc+9rhHhAt3g2aRB3SW61mL5e/SpmYd+JU82ndVriJXoTCs7wSBrIZGOgsUcR6sqlrGBrcUjxZM+deOe20fbEMqLIOwET5Zy7CycQztzQGiPPOUX9O8le0maxQ3pGdQJZWJkzFltOX7uhYLJ5U=
