language: go
go:
- 1.8.x
cache:
  directories:
  - "$HOME/.local"
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker --version
- chmod +x ./test.sh
- pip install --user --upgrade awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- go get
before_script:
script:
- "./test.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- docker build -t meifamily/ptt-alertor .
- eval $(aws ecr get-login --region us-west-2 --no-include-email)
- docker tag meifamily/ptt-alertor:latest $AWS_Docker_Repo:latest
- docker push $AWS_Docker_Repo:latest
deploy:
- provider: script
  script:
  - bash ./deploy/ecs-deploy -r us-west-2 -c Production-Cluster -n Ptt-Aletor -i $AWS_Docker_Repo
    -m 0 -M 100 -t 600 -D 1
  on:
    branch: master
notifications:
  slack: meifamily:9oYnHKf0nlRn8QafX4PRZ1lC
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJETASPZ4NVARC3IA
  - AWS_Docker_Repo=833648024955.dkr.ecr.us-west-2.amazonaws.com/ptt-alertor-repo
  - secure: mT8vyNqYv2z4JTmL4fUxf3tlBiAmkbgoTmxEKHf7yj02Uf4/vU5v+V2j9Seq4/9/9D4YSPmsOriyK86xfvK04bgO66mDp2saEbNalnfyEWoclKCR7kZ5GQtmhXh17ZUp6rFGANqvmHDE4D6hiVBKBJpYNPTAd2XsEeFR+QrqIjYlucMCTNmzOfEOqxoc4/vTKeI1J8LLAfJiSlpgMb33Sbo3evgRlO05j0geN+f9S1yWZPr5UoaqTGiZDbxpmJ1PXGoopmKXwv8TmGxYh9CLPNWx1LGXJ23Mp+CJT1h7UmXrtZ83qjDt0tsYGUTUbShjoBL1IALHcmtHEgM6WGEA4Y1cYBZaiHpthNO8SBpmi0niYSoOTJEAu2gJrt4/R5wfBagP9JcyVRO6Vey3OWEEK1j3+BWc4lxbKEfSJ9u1z4M/mxuTNL5lF5YYSVsIqyH8lmT1ONEnzsI1cU3S/T1+ahOtbKcFPbrlqIMNt9FHu28pfXa5qFqBXnHNbYc6XtOUQU3NQ+9XarZMRKZUw+wIDp/s51K0JVZIMzWiO8fBhRo9aN5N42HK7ozWxngdsmtbYoJPQaQEAPnMhtYtYXJjk1Ef32M43jRKzVljCcbcMCwJZICXLuXleVGeagXKfQu/nAILZ+JO/zqoPNXHfwDUHitAp+d3wf3+FcoNDxkask4=
