language: go
go:
- 1.7.x

services:
   - docker

before_install:
   - docker build -t hello_world docker_golang_1.7
   - docker run -d hello_world /bin/sh -c "ls"
   - docker ps -a


### For codecov
script:
  - sh ./.codecov.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
