language: go
go:
   - 1.7.x

services:
   - docker

before_install:
   - docker build -t ic09272002/hello_world .
   - docker ps -a

#- docker run -d -p 9090:9090 hello_world


### For codecov
script:
   - docker run -d -p 9090:9090 ic09272002/hello_world
after_success:
   - docker login -u=ic09272002 -p=icfordocker
   - docker push ic09272002/hello_world

deploy:
   - provider: s3
     on:
       branch: test_travisCI
      # rest of S3 deployment for MyApp.zip
   - provider: codedeploy
     access_key_id: "AKIAICUDJINSD4HSL7VQ"
     secret_access_key: "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"
     bucket: "S3 Bucket"
     key: latest/MyApp.zip
     application: MyApp
     deployment_group: MyDeploymentGroup
     on:
       branch:test_travisCI
