language: go
go:
- 1.7.x

services:
   - docker

before_install:
   - docker build -t hello_world .
   - docker run -d -p 9090:9090 hello_world
   - docker ps -a


### For codecov
script:
  - sh ./.codecov.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
